name: ci

on:
  push:
  pull_request:
  workflow_dispatch: {}

jobs:
  rust-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo check
        run: cargo check --manifest-path Cargo.toml --locked

      - name: Cargo test
        run: cargo test --manifest-path Cargo.toml --locked --tests

      - name: Cargo fmt
        run: cargo fmt --manifest-path Cargo.toml -- --check

      - name: Cargo clippy
        run: cargo clippy --manifest-path Cargo.toml -- -D warnings
